### ISSUE TITLE
Support to CSS domain for colors, alphas and colors+alphas

### ISSUE THREAD

**Issue by CoffeeStraw** [CoffeeStraw/PyonFX#16]
Right now, PyonFX permits conversions between ASS colors/alphas/colors+alphas as strings to integers and vice versa.

It would be nice to also offer to the user a built-in way to handle rgba colors in CSS domain. This could be usefull, since all the tools available online for color picking (like [this one](https://www.css3maker.com/css-3-rgba.html)) return strings or integer values in CSS domain.

**Comment by CoffeeStraw** [comment]
One of the proposal to implement that is to add an additional function to che `Convert` class, named **`coloralpha_domain`**, with the following usage:
```python
Convert.coloralpha_domain("#111111", css=True) # Converts to &H111111&
Convert.coloralpha_domain("&H111111&", css=True) # Converts to #111111
```
The idea is to leave the conversion _ASS <-> RGBA_ to the `coloralpha` function (which is enough complex as it is), and leaving the conversion _ASS <-> CSS, HSV, ..._ to the new **`coloralpha_domain`**.

We would like to know thoughts about this idea!

**Comment by Youka** [comment]
To make it most flexible there could be a general function for all conversions with variable parameters:
```python
Convert.color(
    input: Union[str, Tuple[int, int, int], Tuple[int, float, float]],
    input_format: ColorEnum,
    output_format: ColorEnum
) -> Union[str, Tuple[int, int, int], Tuple[int, float, float]]
```
For more convenience the library could provide macro functions for simple conversion.
```python
Convert.color_ass_rgb("&H80FF00&")    # (0, 255, 128)
Convert.color_ass_rgb("&H80FF00&", as_str=True)    # #00FF80

Convert.color_rgb_ass((0, 255, 128))    # "&H80FF00&"
Convert.color_rgb_ass("#00FF80")    # "&H80FF00&"

Convert.color_rgb_hsv((0, 255, 128))    # (150, 1.0, 1.0)
Convert.color_ass_hsv("&H80FF00&")    # (150, 1.0, 1.0)

...
```

**Comment by CoffeeStraw** [comment]
I agree on everything (CSS was also not that clear, better to call it just "RGB" like you did), since the actual `coloralpha` function is complex and kinda difficult to understand for users.

In addition to what @Youka said, we will have to implement `Convert.coloralpha` (for every domain, like `Convert.coloralpha_ass_rgba`) and `Convert.alpha`.
