### ISSUE TITLE
Error with latest pywin32

### ISSUE THREAD

**Issue by ShadetHeart** [CoffeeStraw/PyonFX#23]
After updating the library with pip, "import pywin32" results in the following error:
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

This is due to the newest official pywin32 build being faulty.
(Described here: https://github.com/mhammond/pywin32/issues/1598)

A solution to this is using an unofficial pywin32 build:
https://www.lfd.uci.edu/~gohlke/pythonlibs/

1. Download "pywin32‑228‑cp39‑cp39‑win_amd64.whl"
2. run "pip uninstall pywin32"
3. install the downloaded package with "pip install pywin32‑228‑cp39‑cp39‑win_amd64.whl"

Hope this helps anybody running into the same issue and saves them some time.

**Comment by CoffeeStraw** [comment]
Thank you for your issue! I will keep that open until pywin32 will get fixed.
Since some unofficial builds providing a solution already came out, I think it is a matter of days until this issue will get fixed.

**Comment by CoffeeStraw** [comment]
I tried a fresh install of PyonFX using Python 3.9.1 and pywin32 300 (latest version atm of writing) and I do not have any issue on Windows platform. As this issue is Windows-only, I'm going to close the issue, as it seems to be solved.
