### ISSUE TITLE
Some mistakes in the examples file and the docs website

### ISSUE THREAD

**Issue by GilorHatahat** [CoffeeStraw/PyonFX#24]
in the example file "Utilities":

```
# Starting to iterate over the frames
        for s, e, i, n in FU:
            l.layer = 1

            l.start_time = s
            l.end_time = e

            # This lines of codes will reproduce
            # "\\t(0,%d,\\fscx140)\\t(%d,%d,\\fscx100)" % (syl.duration/3, syl.duration/3, syl.duration)
            fsc = 100
            fsc += FU.add(0, syl.duration / 3, 40)
            fsc += FU.add(syl.duration / 3, syl.duration, -40)

            l.text = "{\\an5\\pos(%.3f,%.3f)}%s" % (
                syl.center + random.uniform(-interval, interval),
                syl.middle + random.uniform(-interval, interval),
                syl.text,
            )
```
I think you forgot to add the \fscy tag in the comment 

>  "\\t(0,%d,\\fscx140)\\t(%d,%d,\\fscx100)" % (syl.duration/3, syl.duration/3, syl.duration)

---------------------
in the [pyonfx.utils.FrameUtility](https://pyonfx.readthedocs.io/en/latest/reference/utils.html#pyonfx.utils.FrameUtility) link
on the Add function example:
```
FU = FrameUtility(0, 105, 40)
for s, e, i, n in FU:
    fsc = 100
    fsc += FU.add(0, 50, 50)
    fsc += FU.add(50, 100, -50)
    print(f"Frame {i}/{n}: {s} - {e}; fsc: {fsc}")
>>> Frame 1/3: 0 - 40; fsc: 140.0
>>> Frame 2/3: 40 - 80; fsc: 120.0
>>> Frame 3/3: 80 - 105; fsc: 100
```

this adds 50 

> fsc += FU.add(0, 50, 50)

so fsc should be 150, not 140

and also, from looking at the example file, the correct print should be like this:

```
>>> Frame 1/3: 0 - 40; fsc: 100.0
>>> Frame 2/3: 40 - 80; fsc: 150.0
>>> Frame 3/3: 80 - 105; fsc: 100
```
since we start from 100 and not 140/150.

**Comment by GilorHatahat** [comment]
just found another one in the Utilities example file:
```
# Leadout Effect
        l.layer = 0

        l.start_time = line.start_time + syl.end_time
        l.end_time = line.end_time + delay - 25 * (len(line.syls) - syl.i)
        l.dur = l.end_time - l.start_time

        l.text = "{\\an5\\pos(%.3f,%.3f)\\fad(0,%d)}%s" % (
            syl.center,
            syl.middle,
            delay,
            syl.text,
        )
```
this code applies with every syl including blank ones,
> l.end_time = line.end_time + delay - 25 * (len(line.syls) - syl.i)

so I fixed it by using the Utils.all_non_empty function
> l.end_time = line.end_time + delay - 25 * (len(Utils.all_non_empty(line.syls)) - syl.i)
but I'm sure you can think of more convenient way to do this.

**Comment by CoffeeStraw** [comment]
Hi @GilorHatahat, thanks you for the reports!
1) The first issue you found is true and I edited that comment;
2) The second issue is not an error, but I admit it is a bit confusionary: in that case, frame are defined each 40 ms, while FU.add works with values of 50. So, at 40 ms fsc is equal to 40, not 50;
3) The third issue is true as well, but I think I will need to review the usage of Utils.all_non_empty (since also syl.i is shifted). I will think about that a little bit more.

**Comment by GilorHatahat** [comment]
two problems in the variants example:
1. the star is jumping only on the first and last syls, not all of them.
2. on the third romaji line, the star effect is timed/looks wrong.
