### ISSUE TITLE
wrong line boundaries for an 4 5 6

### ISSUE THREAD

**Issue by SSgumS** [CoffeeStraw/PyonFX#31]
Hello
Unfortunately the library has a strange behavior  when you want to get line's boundary by using `line.left`, `line.right`, `line.top` and `line.bottom` on lines that are `an` 4, 5 or 6. Even in `an` 4 and 6, `line.center` is wrong too.
I prepared a sample for the issue. The zip file attached has the input, script and the output. We can see the middle lines are off in the output.
[Sample File](https://github.com/CoffeeStraw/PyonFX/files/6564322/issue.zip)

**Comment by CoffeeStraw** [comment]
Thank you for your reporting! This issue should be solved in v0.9.10, could you please check if everything is fine?

**Comment by SSgumS** [comment]
> Thank you for your reporting! This issue should be solved in v0.9.10, could you please check if everything is fine?

Yes. It's ok now. Thank you
