### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by CoffeeStraw** [CoffeeStraw/PyonFX#4]
Right now, the library only works for Windows users. However, the library itself is ready for the implementation of Linux's support and shouldn't need any refactoring. More specifically, pretty much all the code is OS independent, except **text's rendering**, used to calculate text's metrics and positions. [Font utility](https://github.com/CoffeeStraw/PyonFX/blob/master/pyonfx/font_utility.py) file is the one dedicated to those operations.

**Comment by fdar0536** [comment]
I have Linux version of Font utility(ytils' fontshandle class), but it implement in c++, and python can access via pybind11. But my implement is not well tested. Maybe you can compile it and try it out.

Here is my repo: https://github.com/fdar0536/SubFX

**Comment by CoffeeStraw** [comment]
Thank you! I will take some time to look into your code and try to figure out a solution. Some months ago I tried to write a solution in Python using [PyGObject](https://lazka.github.io/pgi-docs/), but it doesn't implement all the functions needed and it doesn't appear there is any willing to write them.
