### ISSUE TITLE
Bézier curves

### ISSUE THREAD

**Issue by CoffeeStraw** [CoffeeStraw/PyonFX#5]
Bézier curves should be implemented to help in non-linear movements of text in frame per frame operations.
Support to **quadratic** and **cubic** curves is the priority since they are the most used.

**Comment by Youka** [comment]
How about combining it with #10 ?
Just passing accelerator objects for horizontal and vertical movement to frame-generation method.

**Comment by CoffeeStraw** [comment]
True, there is no point in doing two identical implementations. Thank you for pointing it out!
